config/routes.rb
Rails.application.routes.draw do
  get 'admin/index'         #главное меню администратора
  get 'admin/passwd'        # редактирование профиля администратора
  post 'admin/update_admin' # обновление профиля администратора

  # предметы
  get 'admin/subject'             # страница предметов
  post 'admin/add_subject'        # добавление предмета в БД
  delete 'admin/destroy_subject'  # удаление предмета из БД 

  # преподаватели
  get 'admin/teacher'             # страница преподавателей
  post 'admin/add_teacher'        # добавление нового преподавателя в БД
  get 'admin/update_teacher'      # страница редактирования преподавателя
  post 'admin/update_teacher'     # обновление информации о преподавателе
  delete 'admin/destroy_teacher'  # удаление преподавателя из БД

  # расписание
  get 'admin/schedule'                  # страница информации о расписании
  post 'admin/add_schedule'             # добавление расписания в БД
  get 'admin/new_schedule'              # страница создания расписания класса
  get 'admin/update_class'              # представление редактрирование расписания класса
  post 'admin/update_schedule'          # обновление данных о расписании класса
  delete 'admin/destroy_class_schedule' # удаление расписания одного класса
  delete 'admin/destroy_all_schedules'  # удаление всего расписания школы

  # страница с отображением расписания доступная для всех пользователей
  root to: 'page#home'

  # контроллер сессий
  get 'admin', to: 'sessions#new'         # страница входа в систему
  post 'login', to: 'sessions#create'     # создание новой сессии
  delete 'logout', to: 'sessions#destroy' # выход из системы

  # get 'admin/add'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/admin/index.html.erb
<div class='header'>
  <p class='text-center text'>Администратор расписания</p>
</div>

<div class='container'>
  <div class='text-center main-menu'>
    <h4>Главное меню</h4>
  </div>

  <div id='buttons', class='col-6 offset-3 text-center'>
    <div class='sb'>
      <%= button_to "Предметы", admin_subject_path, method: :get, type: :submit, style: "width: 100%" %>
    </div>
    
    <div class='sb'>
      <%= button_to "Преподаватели", admin_teacher_path, method: :get, type: :submit, style: "width: 100%" %>
    </div>
    
    <div class='sb'>
      <%= button_to "Расписание", admin_schedule_path, method: :get, type: :submit, style: "width: 100%" %>
    </div>

    <div class='sb'>
      <%= button_to "Редактировать профиль", admin_passwd_path, method: :get, type: :submit, style: "width: 100%" %>
    </div>

    <div class='sb'>
      <%= button_to "Выход", logout_path, method: :delete, type: :submit, style: "width: 100%" %>
    </div>

  </div>
  
</div>

app/views/admin/new_schedule.html.erb
<div class='header'>
  <p class='text_adm'>Администратор расписания</p>
  <%= link_to 'На главную', admin_index_path, method: :get, class: 'go_back' %>
</div>

<div class='schedule_form'>

  <%= form_with model: @new_schedule, url: admin_add_schedule_path, method: :post do |f| %>
    <div class='row'>
      <div class='col-4 offset-1'>
        <%= f.label :class_id, 'Класс:' %>
        <%= f.text_field :class_id, placeholder: "Например: 5А" %>
      </div>
      <div class='col-2 offset-1'>
        <%= f.submit 'Добавить' %>
      </div>
    </div>

    <div id='week_schedule'>
      <div class='row'>
        <% 5.times do |ind| %>
          <%= f.fields_for "week_days[#{ind}]" do |t| %>

            <div class='col-6'>
              <div class='week_day text-center'>
                <%= t.label :day, @week[ind] %>
              </div>
              <%= t.hidden_field :day, value: @week[ind] %>

                <div class='schedule_table'>
                  <table class='table table-borderless'>
                    <thead class='text-center'>
                      <tr>
                        <th>№</th>
                        <th>Предмет</th>
                        <th>Преподаватель</th>
                        <th>Начало</th>
                        <th>Конец</th>
                      </tr>
                    </thead>
                    <tbody>
                      <%= t.fields_for :lessons do |l| %>
                        <% 7.times do |count| %>
                          <%= l.fields_for ('1'..'7').to_a[count] do |lesson_fields| %>
                            <tr>
                              <td class='number'>
                                <%= count + 1 %>
                              </td>

                              <td>
                                <%= lesson_fields.fields_for :subject do |sub_field| %>
                                  <%= sub_field.collection_select :id, @lessons, 
                                            :id, :name, include_blank: "", class: "subject" %>
                                <% end %>
                              </td>

                              <td>
                                <%= lesson_fields.fields_for :teacher do |t_field| %>
                                  <%= t_field.collection_select :id, @teachers, 
                                              :id, :FIO, include_blank: "", class: "teacher" %>
                                <% end %>
                              </td>

                              <td>
                                <%= lesson_fields.fields_for :t_start do |st| %>
                                  <%= st.time_select :time, minute_step: 5, start_hour: 9, end_hour: 17,
                                              default: {hour: "0#{count + 9}", minute: "00"} %>
                                <% end %>
                              </td>

                              <td>
                                <%= lesson_fields.fields_for :t_end do |et| %>
                                  <%= et.time_select :time, minute_step: 5, start_hour: 9, end_hour: 17,
                                              default: {hour: "0#{count + 9}", minute: "00"} %>
                                <% end %>
                              </td>
                            </tr>
                          <% end %>
                        <% end %>
                      <% end %>
                    </tbody>
                  </table>
                </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/passwd.html.erb
<div class='header'>
  <p class='text_adm'>Администратор расписания</p>
  <%= link_to 'На главную', admin_index_path, method: :get, class: 'go_back' %>
</div>

<div class='container col-5', style='margin-top: 10vh'>
  <%= form_with model: @admin, url: admin_update_admin_path, method: 'post' do |f| %>

    <%= f.hidden_field :id %>
    
    <div class='row'>
      <%= f.label :login, 'Логин' %>
      <%= f.text_field :login %>
    </div>
    
    <div class='row'>
      <%= f.label :password, "Новый пароль" %>
      <%= f.password_field :password %>
    </div>
    
    <div class='row'>
      <%= f.label :password_confirmation, "Подтвердите пароль" %>
      <%= f.password_field :password_confirmation %>
    </div>
    
    <div class=' text-center row col-3' style='margin: 10px'>
      <%= f.submit 'Обновить' %>
    </div>
  <% end %>
</div>

app/views/admin/schedule.html.erb
<div class='header'>
  <p class='text_adm'>Администратор расписания</p>
  <%= link_to 'На главную', admin_index_path, method: :get, class: 'go_back' %>
</div>

<div class='container'>
	<div id='classes'>
		<table class='table table-borderless text-center'>
			<thead>
				<tr>
					<% 11.times do |ind| %>			<!-- разбитие информации созданного расписания на таблицу по классам -->
						<th><%= ind + 1 %></th>
					<% end %>
				</tr>
			</thead>
			<tbody>
			  <% @classes.each do |array| %>
				  <tr>
						<% 11.times do |t| %>
              <% name = array.grep(/^[#{t + 1}]/) %>
						  <% unless name.empty? %>
								<td><%= link_to name[0],
										  admin_update_class_path(class_id: name[0]) %></td>
							<% else %>
							  <td></td>
							<% end %>
						<% end %>
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>
	<div class='text-center'>
	  <div class='row' style='padding-bottom: 10px'>
  	  	<%= link_to "Добавить класс", admin_new_schedule_path %>
	  </div>
	  <div class='row'>
	  	<%= link_to "Удалить все расписание", admin_destroy_all_schedules_path, method: :delete %>
	  </div>
	</div>

	<div class="message text-center" style='margin: 20px; color: red'>
	  <%= @message %>
	</div>
</div>

app/views/admin/subject.html.erb
<div class='header'>
  <p class='text_adm'>Администратор расписания</p>
  <%= link_to 'На главную', admin_index_path, method: :get, class: 'go_back' %>
</div>

<div class='row'>

  <div class='col-4 offset-1'>
    <h3 class='text-center'>Список предметов</h3>
    <% unless @lessons.empty? %>
      <table class='table table-borderless'>
        <% @lessons.each do |subj| %>
          <tr>
            <td><%= subj.name %></td>
            <td><%= link_to "Удалить", admin_destroy_subject_path(id: subj.id), method: :delete, data: { confirm: "Вы уверены?"} %></td>
          </tr>
        <% end %>
      </table>
    <% else %>
      <p>Список предметов отсутствует<p>
    <% end %>

  </div>
  <div class='col-4 offset-1'>
    <h3>Добавить предмет</h3>
    <%= form_for @new_lesson, url: admin_add_subject_path, method: 'post' do |f| %>

      <div class='row col-7'>
        <%= f.label :name, 'Название' %>
        <%= f.text_field :name %>
      </div>

      <div class='row col-3' style='margin: 10px'>
        <%= f.submit 'Добавить' %>
      </div>

    <% end %>

    <div class='message'>
      <% unless @error.nil? %>
        <p>Невозможно удалить данные, присутствует связь с преподавателем и расписанием</p>
      <% end %>
    </div>
  </div>

</div>

app/views/admin/teacher.html.erb
<div class='header'>
  <p class='text_adm'>Администратор расписания</p>
  <%= link_to 'На главную', admin_index_path, method: :get, class: 'go_back' %>
</div>

<div class='row'>
  <div class='col-7 container'>
    <h3 class='text-center'>Список преподавателей</h3>
    <% unless @teachers.empty? %>

      <table class='table table-borderless text-center'>
        <thead>
          <th>Преподаватель</th>
          <th>Предмет</th>
        </thead>

        <tbody>
          <% @teachers.each do |t| %>
            <tr>
              <td><%= link_to t.FIO, admin_update_teacher_path(id: t.id), method: :post %></td>
              <td><%= t.lessons.map { |el| el.name }.join("/") %></td>
              <td><%= link_to "Удалить", admin_destroy_teacher_path(id: t.id), method: :delete %>
            </tr>
          <% end %>
        </tbody>
      </table>

    <% else %>
      <p>Список преподавателей пуст<p>
    <% end %>
  </div>
  <div class='col-4'>
    <h3>Добавить преподавателя</h3>
    <%= form_with model: @new_teacher, url: admin_add_teacher_path, method: :post do |f| %>

      <div class='row' id='FIO'>
        <%= f.label :FIO, 'Фамилия И.О.' %>
        <%= f.text_field :FIO, class: 'col-8' %>
      </div>

      <% 4.times do |ind| %>
        <div class='row' id='l<%= ind + 1 %>'>
          <%= f.label :lesson, "Предмет #{ind + 1}" %>
          <div class='col-8 select'>
            <%= f.fields_for :lessons do |lesson_fields| %>
              <%= lesson_fields.collection_select :id, @lessons, :id, :name, include_blank: true %>
            <% end %>
          </div>
          <%= f.submit '+', class: 'col-1 offset-1 plus', id: "s#{ind + 1}", type: :button %>
        </div>
      <% end %>

      <div class='row col-3' style='margin: 10px'>
        <%= f.submit 'Добавить', id: "add" %>
      </div>

    <% end %>
  </div>
</div>

<%= javascript_pack_tag 'L_plus', 'data-turbolinks-track': 'reload' %>

app/views/admin/update_class.erb
<div class='header'>
  <p class='text_adm'>Администратор расписания</p>
  <%= link_to 'На главную', admin_index_path, method: :get, class: 'go_back' %>
</div>

<div class='schedule_form'>

  <%= form_with model: @schedule_class, url: admin_update_schedule_path, method: :post do |f| %>
    <div class='row'>
      <div class='class_id col-3 offset-1'>
        <%= f.label :class_id, 'Класс:' %>
        <%= f.text_field :class_id, value: @schedule_class[0].class_id, disabled: true %>
      </div>
      <div class='col-2 offset-1'>
        <%= f.submit 'Обновить' %>
      </div>
    </div>

    <div id='week_schedule'>
      <div class='row'>
        <% 5.times do |ind| %>
          <%= f.fields_for "week_days[#{ind}]" do |t| %>

            <div class='col-6'>
              <div class='week_day text-center'>
                <%= t.label :day, @week[ind] %>
              </div>
              <%= t.hidden_field :day, value: @week[ind] %>

                <div class='schedule_table'>
                  <table class='table table-borderless my_table'>
                    <thead class='text-center'>
                      <tr>
                        <th>№</th>
                        <th>Предмет</th>
                        <th>Преподаватель</th>
                        <th>Начало</th>
                        <th>Конец</th>
                      </tr>
                    </thead>
                    <tbody>
                      <%= t.fields_for :lessons do |l| %>
                        <% 7.times do |count| %>
                          <%= l.fields_for ('1'..'7').to_a[count] do |lesson_fields| %>
                            <tr>
                              <td class='number'>
                                <%= count + 1 %>
                              </td>

                              <td>
                                <% # поиск предметов и преподвателей для отображения в таблице расписания, а так же определение времени  %>
                                <% day_lessons =  @schedule_class.select { |subj| subj.week_day == @week[ind] } %>
                                
                                <%  if day_lessons[count].nil? 

                                      # выбор значений по умолчанию, если данное поле было пустое
                                      selected_subj, selected_teacher = ""
                                      start_hour, start_min = "0#{count + 9}", "00"
                                      end_hour, end_min = "0#{count + 9}", "00"
                                    else
                                      # выбор значений из базы данных
                                      selected_subj = @lessons.find { |sub| sub.id == day_lessons[count].lesson_id }.id
                                      selected_teacher = @teachers.find { |teach| teach.id == day_lessons[count].teacher_id }.id
                                      start_hour, start_min = day_lessons[count].t_start.hour, day_lessons[count].t_start.min
                                      end_hour, end_min = day_lessons[count].t_end.hour, day_lessons[count].t_end.min
                                    end
                                %>

                                <%= lesson_fields.fields_for :subject do |sub_field| %>
                                  <%= sub_field.collection_select :id, @lessons, 
                                        :id, :name, include_blank: "",
                                        selected: selected_subj %>
                                <% end %>
                              </td>

                              <td>
                                <%= lesson_fields.fields_for :teacher do |t_field| %>
                                  <%= t_field.collection_select :id, @teachers, 
                                              :id, :FIO, include_blank: "", selected: selected_teacher %>
                                <% end %>
                              </td>

                              <td>
                                <%= lesson_fields.fields_for :t_start do |st| %>
                                  <%= st.time_select :time, minute_step: 5, 
                                              default: {hour: start_hour, minute: start_min} %>
                                <% end %>
                              </td>

                              <td>
                                <%= lesson_fields.fields_for :t_end do |et| %>
                                  <%= et.time_select :time, minute_step: 5, 
                                              default: {hour: end_hour, minute: end_min} %>
                                <% end %>
                              </td>
                            </tr>
                          <% end %>
                        <% end %>
                      <% end %>
                    </tbody>
                  </table>
                </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/update_teacher.html.erb
<div class='header'>
  <p class='text_adm'>Администратор расписания</p>
  <%= link_to 'На главную', admin_index_path, method: :get, class: 'go_back' %>
</div>

<div class='col-4 container' style='margin-top: 20px'>
  <%= form_with model: @teacher, url: admin_update_teacher_path, method: :post do |f| %>
    <div class='row' id='FIO'>
      <%= f.label :FIO, 'Фамилия И.О.' %>
      <%= f.text_field :FIO, class: 'col-8' %>
    </div>

    <% 4.times do |ind| %>
      <div class='row' id='l<%= ind + 1 %>'>
        <%= f.label :lesson, "Предмет #{ind + 1}" %>
        <div class='col-8 select'>
          <%= f.fields_for :lessons do |lesson_fields| %>
            <%= lesson_fields.collection_select :id, @lessons, :id, :name, include_blank: true %>
          <% end %>
        </div>
        <%= f.submit '+', class: 'col-1 offset-1 plus', id: "s#{ind + 1}", type: :button %>
      </div>
    <% end %>

      <div class='row col-3' style='margin: 10px'>
        <%= f.submit 'Обновить', id: "add" %>
      </div>
  <% end %>
</div>